spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdmh
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:9090/realms/springboot
        jwk-set-uri: http://localhost:9090/realms/springboot/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: dmh
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.http: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      api-account:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.net.SocketTimeoutException
          - java.io.IOException
        ignoreExceptions:
          - com.api.user.exception.UserAlreadyExistsException
  retry:
    instances:
      api-account:
        max-attempts: 3
        wait-duration: 500
        retry-exceptions:
          - java.lang.Exception

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
